language: java
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings_simple.xml
script: mvn clean install deploy
env:
  global:
  - secure: T+ibkKeeLMgCYdapPt5srkS8J7PuyCLMgZ1OJsT1pZbOk8mwgI1MC9LN2gbJoLe/f9s35NUZAz80zcCZfGhOBYMx7RVSy9YpvYw4TCYP5cWhGradiUl3qt5t7mUcN7xjMYwHMBq+/2HvHZCXGjZTNJD8uK0xqXNC7BDZ6/QkMeSbzwyvAAT1mKAHWO3vIDfJL6qw4KUxM7FDhsBykmIVhS9KiaD55BRNwzjJQnz1LRmnCu9is4VuqRfjpZXOZzYP55AlshIpLnyeWhiei4JuOEz42jYmPCHHixVs/TXKApp2KbZtwsR3tZkUgbszXi+YH9J5IR3cLev6HFYxS/xGvD+3RK34VohqEXRnupARpe8o8I60FSs++oZUWZ/9ssMgFr860iFJQOprUjMYxK27FT4Lv+oiq/5eQZFdYMrSvfkAmJ/9Av//VQEh7NQ5u9FQWqZLgbBRJP8s7z1yUoTKJSknFCH2j5WXOmwGK2HxBciq1uofJstS7D/Li+Jw0yA3GzmJWQSXvQ5m2n2JkFolTku1Y0Fhnym+1LdTwXZkgEcoq4ZLjS6tbA5qJTaUbLMKEfi5ZNYhpd6MQkUvV6oov+8h+p2oi9CZn7vIruHGt59VnnDd2wzPDW2hBWjpZrl3KXOw8NOqlbjW17GrNBvlDPqFNFjVRKIv8ICFadqvFOw=
  - secure: Z7oUWtrl2ON4cncS8Y9V+N4cO5ypTvlH/GZgjbEFz4Zn90R1CrjLfrrzYqPyMGdM0mOy62En92IYQehbX9SpuAXzIwVJIQgrb/UR/ha8DyK+KvyaKhpKKMD++4kJmronekCEVVri516ityO94YBWuZR6JKyJ316nbZTkXhIeWkn5QF6TlqRyqFVBe5dpW+DObvoQk4nUnc9tO9QkIsbwfvV2rqQ0RQnXgsefTwBIBFdAWtUUxeYoCkFZ27BONOZuz9T6bN7zqDYqkgsxm17VqdUpeMq8JVhUyUneQELHLs1h9d3FWrrF7zvxinfuvJ5aVLZw3JKhyRze13/Wbbaf92cTXyN1ywZ9dagSiDtz8AxK8dQYamuzid1dZe5YtVBfMBjvaAozGH+xh4Afz35aKX0niwXt9U9Z8YaOpbiW3JyUa8wYp4sFxBxK+QS/MBlRpaaMM6Oj/dGL4DYT1TV6nWvUifDDdx2PZEe1A2l5UR3yix6dqhveGoKRhxspM1c5YhUaH/A//A+YPhe+V2P7Il2dwdglrwo/Iq8gLsci1HFSSLfdlTsURNydOfbXmJs40+tLPzR/h3ThkgnWvpLQfOGFONF8Q6bFp7o90/iU0vNf3kdVEmx+d+qTgOdHs1khxXm7POzI2Cnp9q5TpEuzp3Gm62kK2R1zYR7kMrm8eIs=
