language: java
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
script: mvn clean install deploy
env:
  global:
  - secure: SVue0Y0ZEKPHWQzjSL+FeGDRTgtEG9V+U2mgZjSNp+AU/GO03JWW+GxCsp4V7+EluL+yz+o0hRvQ25wAfvglZ0rXvfMADsJhPNvrBfMBde9Mcph0gHJXsaQG0H72Osr3auFThPr9rK/u5BQ1SEpdJmy1wLdQPS+wh0zSwvd6VG2TtnhZ8NS6knTM4h+Q9B/TisEtugIrzjBswr1eFpJ60qokdSmpGkYlfMQxen1kZTuqFBy1e0lK7CmXTnM59T7QI5PAVcHd0wL4Gg9htWDkPVXlw5QE8/1zhzvtF9bm4M+mklZo7VETaZAmZskk+ugu8dJ3p1eMsLxJvLMNQReqtHM0h/PT5js+l5fGFXtVyPTF+5Ta735/wSsFx7DlSDTrNvZJElGiHcgHc1bNJG15aiAd7oczkzZzhVf4n7CvY6XwPlECBSAj8f1jqA5xiA+xyaiDhxgGmX7dRpapiG5dHakecSJlHKCWGdrlCnEN+9eMmU0YDAl3kfzO/DfUOXuZnoLomLpJFDKZfa6t3e1QzEr9m+bxEXG3Au+BXW7rirvFQkCwV4S8UKhT1cdTMWmQ7ekrUxZBPLIjGDCFW6EOveSd+jprMLZaFW+Cfu9757C3jzKcuA4fG6ETo9EHn3nPbse4eIM4MhflcgQdqD1nTW2JFDmvud3O378n5kVCZYo=
  - secure: Idj0EB00VKWrlPBZVoUnUUXhC1ZcSZJZJ0RJB5a1r4x5tPAXnU8FdD+nQDH1UiYdmqEh8uZsKo4jg7h8woX/ya1KbT8T1OpUSm8G14DTHWc7WnJ2S80ZxcS5Zfe74wY07HKxpQgzr+3tPsqSbsPYW06suRDJLIC62uNbfG6JAwLm0dUGiMHgWP8fwQPMPlagrEwx1i++z35COTh6bMxSvTfiy3fVHSz8dynvzdN+dfuWLClYrQJUxb2H2QmOTc6K1ydPODt5LdI2IX0AG/Bo40hg1+qW/vhqooKuYlweOj4Crdvw8WHDfHLjQXPPBfjfMc/7bl4JmcABzJm++o1s09AGDwFZ6V1zHQetPT5a7+dsf3iZQO5NM1ivantwfARGzR6nDa/FifUyHHhjmu+DiV+r2TpfhooXydJvYdfejlO7JyAInwKJT1iEK46ysAnGKg1zquSQ4uogfSH05ZCNCWxUC+xpYOFd84fY52e5hvdWApYEsCVsQeIKL+MJXr2VDkRx4MJ+P9igkOlyYyt6VmXBDVEzb3NxYjPsRZsjeLKeyWo2UfVTnFllh6SvTizRUtyBW7mSCWElYfwDEJAZCt+EZn/AMWKN8H0sjf3V5Z/tObT+Q4gRPK4kwmuRJ5nFP2LtRoDIGPhDYqP62dtibgt4UGspHYOHGoEsYQa/MD8=
